In [5]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'new_cases': [38820.0, 33071.0, 33383.0, 39444.0, 41640.0, 41503.0, 43654.0],
                   'new_deaths': [4368.0, 4678.0, 5211.0, 5093.0, 5071.0, 5495.0, 5581.0],
                   'new_tests': [396534.0, 623338.0, 658639.0, 655283.0, 745288.0, 657200.0, 543174.0]},
                  index=[0, 1, 2, 3, 4, 5, 6])

# Create a styler object
styler = df.style

# Apply styling methods
styler.background_gradient()

# Export the styled DataFrame as HTML

# You can then save the HTML to a file or display it in a Jupyter notebook

In [6]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'new_cases': [38820.0, 33071.0, 33383.0, 39444.0, 41640.0, 41503.0, 43654.0],
                   'new_deaths': [4368.0, 4678.0, 5211.0, 5093.0, 5071.0, 5495.0, 5581.0],
                   'new_tests': [396534.0, 623338.0, 658639.0, 655283.0, 745288.0, 657200.0, 543174.0]},
                  index=[0, 1, 2, 3, 4, 5, 6])

# Create a styler object
styler = df.style

# Define styling functions
def highlight_min_max(styler):
    
    styler.highlight_min(color='lightgreen')
    styler.highlight_max(color='red')
    return styler

def add_border(styler):
    styler.set_properties(**{'border': '2px solid black'})
    return styler

# Apply styling functions using pipe
styled_df = styler.pipe(highlight_min_max).pipe(add_border)

# Render the styled DataFrame in a Jupyter notebook
styled_df

In [7]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'new_cases': [38820.000000, 33071.000000, 33383.000000, 39444.000000, 41640.000000, 41503.000000, 43654.000000],
                   'new_deaths': [4368.000000, 4678.000000, 5211.000000, 5093.000000, 5071.000000, 5495.000000, 5581.000000],
                   'new_tests': [396534.000000, 623338.000000, 658639.000000, 655283.000000, 745288.000000, 657200.000000, 543174.000000]},
                  index=[0, 1, 2, 3, 4, 5, 6])

# Create a styler object
styler = df.style

In [8]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'new_cases': [38820.000000, 33071.000000, 33383.000000, 39444.000000, 41640.000000, 415.000000, 43654.000000],
                   'new_deaths': [4368.000000, 4678.000000, 5211.000000, 564.000000, 5071.000000, 5495.000000, 5581.000000],
                   'new_tests': [396534.000000, 623338.000000, 658639.000000, 655283.000000, 745.000000, 657200.000000, 543174.000000]},
                  index=[0, 1, 2, 3, 4, 5, 6])

# Create a styler object
styler = df.style

# Define a function to change the text color
def change_text_color(val):
    color = 'darkblue' if val >= 1000 else 'darkorange'
    return f'color: {color}'

# Apply the function to the styler object
styled_df = styler.applymap(change_text_color)

# Render the styled DataFrame in a Jupyter notebook
styled_df

In [9]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'new_cases': [38820.0, 33071.0, 33383.0, 39444.0, 41640.0, 41503.0, 43654.0],
                   'new_deaths': [4368.0, 4678.0, 5211.0, 5093.0, 5071.0, 5495.0, 5581.0],
                   'new_tests': [396534.0, 623338.0, 658639.0, 655283.0, 745288.0, 657200.0, 543174.0]},
                  index=[0, 1, 2, 3, 4, 5, 6])

# Create a styler object
styler = df.style

# Define a function to apply conditional styling
def apply_conditional_style(val):
    if val > 35000:
        return 'background-color: lightgreen'
    else:
        return 'background-color: red'

# Apply the function to every value in the DataFrame
styled_df = styler.applymap(apply_conditional_style)

# Define a CSS style for the borders
border_style = 'border: 1px solid black;'

# Apply the border style to the DataFrame
styled_df = styler.set_table_styles([{'selector': 'table', 'props': border_style},
                                     {'selector': 'th', 'props': border_style},
                                     {'selector': 'td', 'props': border_style}])

# Render the styled DataFrame in a Jupyter notebook
styled_df

Section 6.9 Debugging of your textbook lists three possibilities to consider if a function is not working.

Describe each possibility in your own words.

Define "precondition" and "postcondition" as part of your description.

Create your own example of each possibility in Python code. List the code for each example, along with sample output from trying to run it.
The code and its output must be explained technically whenever asked. The explanation can be provided before or after the code, or in the form of code comments within the code. For any descriptive type of question, Your answer must be at least 150 words.

End your discussion post with one question related to programming fundamentals learned in this unit from which your colleagues can formulate a response or generate further discussion. Remember to post your initial response as early as possible, preferably by Sunday evening, to allow time for you and your classmates to have a discussion.

In [24]:
def divide(x, y):
    return x / y

result = divide("X", 1.5)
print(result)

TypeError: unsupported operand type(s) for /: 'str' and 'float'

In [6]:
Bug:

Debugging: 
When an error occur after we run a code, the process of examining and or identifying the cause of the error 
and resolving or fixing the bugs in a program is called debugging. 

Three possibility factors to consider if the function is not working:

1. Precondition Violation: refers to a condition or set of conditions that must be true 
before a particular block of code or function is executed.
If there is something wrong with the arguments the function is receiving, it means that a precondition is violated.

#For instance, let's try to divide a string and a floating number 
# Precondition Violation
def divide(x, y):
    return x / y

result = divide("X", 1.5)
print(result)  # Output: ZeroDivisionError: division by zero

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[11], line 4
      1 def divide(x, y):
      2     return x * b
----> 4 result = divide("X", 1.5)
      5 print(result)

Cell In[11], line 2, in divide(x, y)
      1 def divide(x, y):
----> 2     return x * y

TypeError: can't multiply sequence by non-int of type 'float'
        
# This error occured because a float number is inputed instaed of an int number. 

# Meaning, we can only multiply an integer with a string.
        



2. Postcondition Violation: A postcondition is a condition that is expected
to be true after the execution of a particular block of code or function. 
If preconditions are satisfied but the function still does not work well, it means that a bug is in the function itself.

# An instance of Postcondition Violation
def full_name(first_name, last_name):
    print(f'Hello' last_name, 'how are you doing today?')
    #If we forget to include the first_name parameter in the print statement
    #it will work but would not display the desired result. 


full_name('Solomon', "Ajegbeyi")



output: Hello Ajegbeyi how are you doing today?
# By looking at this output i was expecting my full name but it gave only last_name which means that the function 
#has a bug i need to fix in the print statement. 




3.Return Value Error: If we encounter this type of error after calling a statement or a funtion
it means that there's a 
problem with the values been retured, due to incorrect logic within the statement or  function.

#Let's see this simple example of a ValueError.
name ="Python"
age= int("Python")

print(name,'programming language is', age 'years old.')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[16], line 2
      1 name ="Python"
----> 2 age= int("Python")
      4 print(name,'programming language is', age, 'years old.')

ValueError: invalid literal for int() with base 10: 'Python'

#This error was raised because i tried to convert the python string to an integer.
#To get the correct output this is what must be written.
#age= len("Python")  or
#age= int(len("Python"))


(1) debugging - precondition, postcondition and return value - Stack Overflow. https://stackoverflow.com/questions/64141285/precondition-postcondition-and-return-value.
(2) 19.9: Debugging - Engineering LibreTexts. https://eng.libretexts.org/Bookshelves/Computer_Science/Programming_Languages/Think_Python_-_How_to_Think_Like_a_Computer_Scientist_%28Downey%29/19%3A_Fruitful_Functions/19.09%3A_Debugging.
(3) Debugging | Open Textbooks for Hong Kong. https://www.opentextbooks.org.hk/ditatopic/25850.
(4) Discussion Assignment 4 - Describe each possibility in your ... - Studocu. https://www.studocu.com/en-us/document/university-of-the-people/programming-fundamentals/discussion-assignment-4/12134536.

SyntaxError: invalid decimal literal (3064749246.py, line 71)

In [ ]:
In programming, a precondition is a condition that must be true before a function or method can be executed. It is a requirement that must be met by the caller of the function. A postcondition, on the other hand, is a condition that must be true after a function or method has been executed. It is a guarantee made by the function to the caller.

Here is an example of a function with preconditions and postconditions in Python:

```python
def divide(a, b):
    """
    Divides two numbers and returns the result.

    Preconditions:
    - b must not be zero.

    Postconditions:
    - The result is the quotient of a and b.
    """
    if b == 0:
        raise ValueError("b must not be zero.")
    result = a / b
    return result
```

In this example, the `divide` function has a precondition that `b` must not be zero. If `b` is zero, the function raises a `ValueError`. The postcondition is that the result is the quotient of `a` and `b`.

Here is an example of a function that violates a precondition:

```python
def divide(a, b):
    """
    Divides two numbers and returns the result.

    Preconditions:
    - b must not be zero.

    Postconditions:
    - The result is the quotient of a and b.
    """
    result = a / b
    return result
```

If we call this function with `b` equal to zero, a `ZeroDivisionError` will be raised:

```python
>>> divide(10, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in divide
ZeroDivisionError: division by zero
```

Here is an example of a function with a postcondition:

```python
def square(x):
    """
    Returns the square of a number.

    Postconditions:
    - The result is the square of x.
    """
    result = x ** 2
    return result
```

In this example, the `square` function has a postcondition that the result is the square of `x`.

Here is an example of a function that violates a postcondition:

```python
def square(x):
    """
    Returns the square of a number.

    Postconditions:
    - The result is the square of x.
    """
    result = x * 2
    return result
```

If we call this function with `x` equal to `3`, the result will be `6`, which violates the postcondition:

```python
>>> square(3)
6
```

I hope this helps! Let me know if you have any other questions.

Source: Conversation with Bing, 9/28/2023
(1) precondition, postcondition and return value - Stack Overflow. https://stackoverflow.com/questions/64141285/precondition-postcondition-and-return-value.
(2) Preconditions and Postconditions - New York University. https://cse.engineering.nyu.edu/~mleung/CS1114/s09/ch05/pre_post.htm.
(3) Functions and procedures - Kansas State University. https://people.cs.ksu.edu/~schmidt/301s11/Lectures/3procS.html.
(4) Preconditions and Postconditions – HeelpBook. https://www.heelpbook.net/2016/preconditions-and-postconditions/.
(5) Python @precondition / @postcondition for member function - how?. https://stackoverflow.com/questions/12151182/python-precondition-postcondition-for-member-function-how.
(6) Error python : [ZeroDivisionError: division by zero]. https://stackoverflow.com/questions/29836964/error-python-zerodivisionerror-division-by-zero.
(7) ZeroDivisionError Division by Zero in Python - Codeigo. https://codeigo.com/python/zerodivisionerror-division-by-zero/.
(8) python - How to deal with "divide by zero" with pandas dataframes when .... https://stackoverflow.com/questions/38886512/how-to-deal-with-divide-by-zero-with-pandas-dataframes-when-manipulating-colum.
(9) Handle Zero Division Error In Python - Pythondex. https://pythondex.com/handle-zero-division-error-python.
(10) undefined. https://wiki.python.org/moin/HandlingExceptions.

This assignment will assess your skills and knowledge in developing a function through an incremental development process such that the debugging becomes fast. There are two parts of this assignment, and you must submit both parts.

Part 1

You work as a software developer in a company that creates custom software solutions for various clients. Your company has been approached by an educational client who wants to develop a function that calculates the length of the hypotenuse of a right triangle given the lengths of the other two legs as arguments. Your manager has instructed you to use incremental development to create the necessary function and document each stage of the development process. After completing the final stage of development, you have to test the function with different arguments and record the outputs in your Learning Journal.

Tasks Include all of the following in your submission:

An explanation of each stage of development, including code and any test input and output. The output of hypotenuse(3,4). The output of two additional calls to hypotenuse with different arguments.

In [4]:
def simple_interest(p, r, t):

    """Calculating the Simple interest of an amount given the principal, rate% and time taken.

    Preconditions:
    p, r and t must be positive.

    Postconditions:
    - The result is the product of  (p*r*t)/100.
    """
    if p <= 0 or r <= 0 or t <= 0:
        raise ValueError("The input values must be positive.")
    SI = (p* r * t) / 100
    return SI


#Testing the function to see if it’s working properly. 
#Here are some examples:


simple_interest(1000, 10, 2)

output: 200
    

simple_interest(1e8,5,10)    

output: 5e7

50000000.0

 You are a software developer who wants to establish yourself as a skilled and versatile programmer. To achieve this, you have decided to create a work portfolio that showcases your ability to develop custom software solutions. This portfolio will be your gateway to attract potential clients and establish yourself as a freelancer. 

As part of your portfolio, you plan to create your own function that does some useful computation using an incremental development approach that will demonstrate your programming skills and problem-solving abilities. You will document each stage of the development process, including the code and any test input and output in your Programming Assignment.

In [10]:



def factorial(n):
    """
    Calculates the factorial of a number.

    Preconditions:
    n must be non-negative.

    Postconditions:
    The result is the factorial of n.
    """
    if n < 0:
        raise ValueError("The input value must be non-negative.")
    if n == 0:
        return 1
    else:
        return n * (n-1)



factorial(5)

""">>> factorial(1)
1
>>> factorial(5)
120
>>> factorial(10)
3628800"""

'>>> factorial(1)\n1\n>>> factorial(5)\n120\n>>> factorial(10)\n3628800'

In [11]:
def factorial(n):
    
    """
    Calculates the factorial of a number.

    Preconditions:
    n must be non-negative.

    Postconditions:
    The result is the factorial of n.
    """
    
    if n < 0:
        return None
    elif n == 0:
        return 1
    else:
        return n * factorial(n-1)

n = int(input("Enter a number: "))
result = factorial(n)

if result is None:
    print("Factorial is not defined for negative numbers.")
else:
    print(f"The factorial of {n} is {result}.")

Enter a number: 15
The factorial of 15 is 1307674368000.

This program prompts the user to enter a number and calculates its factorial using recursion. If the user enters a negative number, the program returns None and prints an error message. If the user enters 0, the program returns

In [ ]:
To develop a function that calculates the length of the hypotenuse of a right triangle given the lengths of the other two legs as arguments, we can use incremental development. Incremental development is a process that involves adding and testing only a small amount of code at a time to avoid long debugging sessions.

Here are the stages of development for the hypotenuse function:

1. Define the function hypotenuse with two parameters, `leg1` and `leg2`, and return 0.0.


def hypotenuse(leg1, leg2):
    return 0.0


2. Calculate the sum of squares of `leg1` and `leg2` and store it in a variable called `sum_of_squares`. Return `sum_of_squares`.


def hypotenuse(leg1, leg2):
    sum_of_squares = leg1 ** 2 + leg2 ** 2
    return sum_of_squares


3. Calculate the square root of `sum_of_squares` using the `sqrt()` function from the `math` module. Return the result.


import math

def hypotenuse(leg1, leg2):
    sum_of_squares = leg1 ** 2 + leg2 ** 2
    hypotenuse = math.sqrt(sum_of_squares)
    return hypotenuse

Final stage of development is completed, let's test the function with different arguments:


print(hypotenuse(3, 4))
print(hypotenuse(5, 12))
print(hypotenuse(8, 15))
```

The output of these calls to `hypotenuse` are: